source :rubygems
ruby '2.7.3'

gem 'sinatra', '>= 2.0.2'
gem 'haml'
gem 'oauth'
gem 'json', '>= 2.3.0'
gem 'mongo', '~> 2.3'
gem 'mongoid', '~> 6'
gem 'bson_ext', '~> 1.3.1'
gem 'string-pad', :require => 'string/pad'
gem 'rack_csrf', :require => 'rack/csrf'
gem 'twitter', '~> 6'
gem 'sinatra-flash', :require => 'sinatra/flash'
gem 'activesupport', '>= 5.2.4.3'
